strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_10_x:
      node_version: 10.x
    node_12_x:
      node_version: 12.x
    node_13_x:
      node_version: 13.x

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'

- script: |
    npm install --global yarn@latest
  displayName: 'install dependencies'

- script: |
    yarn bootstrap
    yarn lint
    yarn build
    yarn bundle
    yarn test
  displayName: 'build & test'
