name: Publish GitHub release
description: Publishes a new release on GitHub

inputs:
  token:
    description: A GitHub access token
    required: true

runs:
  using: node12
  main: main.js

branding:
  icon: github
