name: Assets

on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  assets:
    name: Update local assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use node 13
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn bootstrap

      - name: Fetch latest assets
        id: fetch
        working-directory: ./packages/adblocker/assets
        run: |
          ./update_lists.sh

      - name: Generate compression codebooks
        id: codebooks
        working-directory: ./packages/adblocker/
        run: |
          yarn generate-codebooks

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN_PR }}
          committer: Rémi Berson <remusao@users.noreply.github.com>
          commit-message: "chore: update local assets"
          title: "Update local assets"
          body: "Automated update of local assets."
          labels: "PR: Internal :house:"
          reviewers: remusao
          branch: update-assets

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
